/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ca08a67e16f5a0fc36578e8f15fdc84)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	CF_MODE: "mock";
	DRY_RUN: "true";
	PROTECTED_NAMES: "www,mail,api";
	OPENROUTER_MODEL: "openrouter/free";
	ADMIN_SECRET: string;
	OPENROUTER_API_KEY: string;
	GraveyardAgent: DurableObjectNamespace<import("./src/index").GraveyardAgent>;
	ResourceBiography: DurableObjectNamespace<import("./src/index").ResourceBiography>;
	MockZone: DurableObjectNamespace<import("./src/index").MockZone>;
	RealZone: DurableObjectNamespace /* RealZone */;
	QUARANTINE_WORKFLOW: Workflow<Parameters<import("./src/index").QuarantineWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "GraveyardAgent" | "ResourceBiography" | "MockZone" | "RealZone";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_MODE" | "DRY_RUN" | "PROTECTED_NAMES" | "OPENROUTER_MODEL" | "ADMIN_SECRET" | "OPENROUTER_API_KEY">> {}
}
