/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a6966be9f1d03958407353561ce21761)
interface __BaseEnv_Env {
	CF_MODE: "mock";
	DRY_RUN: "true";
	PROTECTED_NAMES: "www,mail,api";
	OPENROUTER_MODEL: "openrouter/free";
	GraveyardAgent: DurableObjectNamespace<import("./src/index").GraveyardAgent>;
	ResourceBiography: DurableObjectNamespace<import("./src/index").ResourceBiography>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "GraveyardAgent" | "ResourceBiography";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_MODE" | "DRY_RUN" | "PROTECTED_NAMES" | "OPENROUTER_MODEL">> {}
}
